In [141]:
import seaborn as sns
data=sns.load_dataset('iris')
data.shape

(150, 5)

In [142]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [143]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [144]:
data.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [145]:
X = data.drop('species', axis=1)
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [146]:
y = data['species']
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [147]:
y.value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [148]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y=le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [149]:
le.inverse_transform([0,1,2])

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [150]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [151]:
X_train, X_test, y_train, y_test=train_test_split(X, y)

In [152]:
X_train.shape

(112, 4)

In [153]:
y_train.shape

(112,)

In [154]:
X_test.shape

(38, 4)

In [155]:
y_test.shape

(38,)

In [156]:
logreg= LogisticRegression()
logreg.fit(X_train, y_train)

LogisticRegression()

In [157]:
y_pred = logreg.predict(X_test)
y_pred

array([0, 1, 1, 2, 2, 0, 2, 0, 0, 2, 1, 0, 2, 2, 1, 1, 0, 2, 1, 0, 1, 1,
       0, 0, 2, 1, 0, 2, 0, 0, 0, 1, 2, 2, 1, 0, 2, 1])

In [158]:
y_test

array([0, 1, 1, 2, 2, 0, 2, 0, 0, 2, 1, 0, 2, 2, 1, 1, 0, 2, 1, 0, 1, 1,
       0, 0, 2, 1, 0, 2, 0, 0, 0, 1, 2, 2, 1, 0, 2, 1])

In [159]:
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

In [160]:
accuracy= accuracy_score(y_test, y_pred)
print('Accuracy Score')
print(accuracy)

Accuracy Score
1.0

In [161]:
results_df= pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred
})
print(results_df)

    Actual  Predicted
0        0          0
1        1          1
2        1          1
3        2          2
4        2          2
5        0          0
6        2          2
7        0          0
8        0          0
9        2          2
10       1          1
11       0          0
12       2          2
13       2          2
14       1          1
15       1          1
16       0          0
17       2          2
18       1          1
19       0          0
20       1          1
21       1          1
22       0          0
23       0          0
24       2          2
25       1          1
26       0          0
27       2          2
28       0          0
29       0          0
30       0          0
31       1          1
32       2          2
33       2          2
34       1          1
35       0          0
36       2          2
37       1          1

In [162]:
user_data=pd.DataFrame({
    'sepal_length':[5.1],
    'sepal_width':[3.5],
    'petal_length':[1.4],
    'petal_width':[0.2]
})
sepal_length=input('enter sepal length')
sepal_width=input('enter sepal width')
petal_length=input('enter petal length')
petal_width=input('enter petal width')
user_data['sepal_length']=sepal_length
user_data['sepal_width']=sepal_width
user_data['petal_length']=petal_length
user_data['petal_width']=petal_width
ai_predict=logreg.predict(user_data)
ai_predict

enter sepal length5
enter sepal width5
enter petal length5
enter petal width5

array([2])

In [163]:
decoded_predict=le.inverse_transform(ai_predict)
user_data['species']=decoded_predict
print(user_data)

  sepal_length sepal_width petal_length petal_width    species
0            5           5            5           5  virginica

In [164]:
print('Species is : ', decoded_predict)

Species is :  ['virginica']